config/routes.rb
Plato::Application.routes.draw do
  get "game2/index"

  get "game2/getEvents"

  get "game2/fireEvent"

  get "facebook/index"

  devise_for :users

  get "game/index"
  get "game/dropBomb"
  get "game/playerMoved"
  get "game/restart"
  get "game/pollGameState"
  get "game/savePhone"

  resources :users

  resources :bombs
  match "facebook" => "facebook#index"
  root :to => "game#index"

end

app/models/bomb.rb
class Bomb < ActiveRecord::Base
  include BombsHelper
  include ApplicationHelper

  acts_as_mappable :default_units => :kms,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :latitude,
                   :lng_column_name => :longitude
  def setDuration
    self.duration = serverCalcDuration(self.distance_from(User.find(self.owner_id), :units => :kms) * 1000)
    self.detonatetime = self.createtime + self.duration.seconds
    self.save
  end


  def isExploded?
    if self.did_explode == nil || self.did_explode == false
      return false
    else
      return true
    end
  end

  def explode(curTime)
    # cause this bomb to blow, kill people caught in radius
    self.usersInRange.each do |user|
      damage = damageFor(self.distance_from(user, :units => :kms))
      user.hitWith(damage)
      if user.hp <= 0
        event(:type => 'kill', :data => 'lat: ' + self.latitude.to_s + '; long: ' + self.longitude.to_s + '; target_id: ' + user.id.to_s + '; bomb_id: ' + self.id.to_s + ';');
      else
        event(:type => 'hit', :data => damage.to_s + '; hp: ' + user.hp.to_s + '; lat: ' + user.latitude.to_s + '; long: ' + user.longitude.to_s + '; target_id:' + user.id.to_s + '; bomb_id: ' + self.id.to_s + ';')
      end
      user.notify(sprintf("You just got hit by a bomb which was thrown by %s.  This did %d damage to you and you now have %d hitpoints left", User.find(self.owner_id).name, damage, user.hp))
    end
    self.did_explode=true
    self.save
    User.where(:bomb_id => self.id).each do |u|
      u.bomb_id = nil
      u.save
    end
  end

  def usersInRange
    return User.where(["hp > 0"]).within(BOMB_RADIUS, :origin => [self.latitude,self.longitude])
  end

  def timeLeft
    timeLeft = self.duration.seconds-(Time.now-self.createtime) # this will result in the seconds left till it explodes
    if(timeLeft < 0)
      return 0
    else
      return timeLeft
    end
  end
  scope :explodeBefore, lambda{|endTime| where(["detonatetime < ? and did_explode = false",endTime])}
end

app/controllers/bombs_controller.rb
class BombsController < ApplicationController
  # GET /bombs
  # GET /bombs.xml
  def index
    @bombs = Bomb.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bombs }
    end
  end

  # GET /bombs/1
  # GET /bombs/1.xml
  def show
    @bomb = Bomb.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bomb }
    end
  end
end

app/helpers/bombs_helper.rb
module BombsHelper
  VELOCITY = 2.08333333 # the number of meters traveled per second, so 500 meters covered in 30 seconds => 1000 m/min = 16.67 m/s
  ACCELERATION = 0.00868055554 #  accel = meter/second/second, this means that in 60 seconds is will have increased m/s by 16.67 m/s if a=.2778

  def serverCalcDuration(distance)
    time = (-VELOCITY+Math.sqrt(VELOCITY*VELOCITY+2*ACCELERATION*distance))/(ACCELERATION)
    return time
  end

  def clientCalcDuration
    # this should return a function which is the 'duration' function so it can be called in javascript from the client
    timeStr = "(-#{VELOCITY}+Math.sqrt(#{VELOCITY}*#{VELOCITY}+2*#{ACCELERATION}*distance))/(#{ACCELERATION})"
    return timeStr
  end

  def damageFor(distance)
    # the damage dealt across the BOMB_RADIUS changes from 1 to 0 as one moves away from the epicenter
    # so a perfect direct hit will kill a person instantly, but any little bit off, and they will take at least another shot
    (USER_HITPOINTS * (BOMB_RADIUS - distance) / BOMB_RADIUS).ceil
  end
end

app/views/bombs/_form.html.erb
<%= form_for(@bomb) do |f| %>
  <% if @bomb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bomb.errors.count, "error") %> prohibited this bomb from being saved:</h2>

      <ul>
      <% @bomb.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :createtime %><br />
    <%= f.datetime_select :createtime %>
  </div>
  <div class="field">
    <%= f.label :detonatetime %><br />
    <%= f.datetime_select :detonatetime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bombs/edit.html.erb
<h1>Editing bomb</h1>

<%= render 'form' %>

<%= link_to 'Show', @bomb %> |
<%= link_to 'Back', bombs_path %>

app/views/bombs/index.html.erb
<h1>Listing bombs</h1>

<table>
  <tr>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Createtime</th>
    <th>Detonatetime</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bombs.each do |bomb| %>
  <tr>
    <td><%= bomb.latitude %></td>
    <td><%= bomb.longitude %></td>
    <td><%= bomb.createtime %></td>
    <td><%= bomb.detonatetime %></td>
    <td><%= link_to 'Show', bomb %></td>
    <td><%= link_to 'Edit', edit_bomb_path(bomb) %></td>
    <td><%= link_to 'Destroy', bomb, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bomb', new_bomb_path %>

app/views/bombs/new.html.erb
<h1>New bomb</h1>

<%= render 'form' %>

<%= link_to 'Back', bombs_path %>

app/views/bombs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Latitude:</b>
  <%= @bomb.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @bomb.longitude %>
</p>

<p>
  <b>Createtime:</b>
  <%= @bomb.createtime %>
</p>

<p>
  <b>Detonatetime:</b>
  <%= @bomb.detonatetime %>
</p>


<%= link_to 'Edit', edit_bomb_path(@bomb) %> |
<%= link_to 'Back', bombs_path %>